-- =====================================================================
-- WorkNear initial schema
-- All timestamps are TIMESTAMPTZ (UTC). UUID PKs generated by the app.
-- =====================================================================

-- ---------- Users & identity ----------
CREATE TABLE users (
    id          UUID PRIMARY KEY,
    phone       VARCHAR(20)  NOT NULL UNIQUE,
    role        VARCHAR(20)  NOT NULL,
    full_name   VARCHAR(120),
    email       VARCHAR(160),
    avatar_url  VARCHAR(512),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_users_role ON users(role);

CREATE TABLE customer_addresses (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label       VARCHAR(40),
    line1       VARCHAR(200) NOT NULL,
    line2       VARCHAR(200),
    city        VARCHAR(80),
    state       VARCHAR(80),
    pincode     VARCHAR(12),
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    is_default  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_addresses_user ON customer_addresses(user_id);

-- ---------- Professional ----------
CREATE TABLE professional_profiles (
    id                  UUID PRIMARY KEY,
    user_id             UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    bio                 TEXT,
    experience_years    INT NOT NULL DEFAULT 0,
    service_radius_km   INT NOT NULL DEFAULT 8,
    city                VARCHAR(80),
    area                VARCHAR(120),
    base_latitude       DOUBLE PRECISION,
    base_longitude      DOUBLE PRECISION,
    languages           VARCHAR(200),
    online              BOOLEAN NOT NULL DEFAULT FALSE,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'UNSUBMITTED',
    rating              NUMERIC(3,2) NOT NULL DEFAULT 0,
    rating_count        INT NOT NULL DEFAULT 0,
    jobs_completed      INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_pro_verification ON professional_profiles(verification_status);
CREATE INDEX idx_pro_online ON professional_profiles(online);
CREATE INDEX idx_pro_geo ON professional_profiles(base_latitude, base_longitude);

CREATE TABLE service_categories (
    id          UUID PRIMARY KEY,
    slug        VARCHAR(60) NOT NULL UNIQUE,
    name        VARCHAR(80) NOT NULL,
    icon        VARCHAR(40),
    color       VARCHAR(16),
    sort_order  INT NOT NULL DEFAULT 0,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE professional_services (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL REFERENCES professional_profiles(id) ON DELETE CASCADE,
    category_id     UUID NOT NULL REFERENCES service_categories(id),
    base_price      NUMERIC(12,2) NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    UNIQUE (professional_id, category_id)
);
CREATE INDEX idx_pro_services_category ON professional_services(category_id);

CREATE TABLE professional_specializations (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL REFERENCES professional_profiles(id) ON DELETE CASCADE,
    label           VARCHAR(80) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_pro_spec_pro ON professional_specializations(professional_id);

CREATE TABLE professional_availability (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL REFERENCES professional_profiles(id) ON DELETE CASCADE,
    day_of_week     INT NOT NULL,         -- 1=Mon .. 7=Sun (ISO)
    start_time      TIME NOT NULL,
    end_time        TIME NOT NULL,
    available       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_pro_avail_pro ON professional_availability(professional_id);

CREATE TABLE professional_documents (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL REFERENCES professional_profiles(id) ON DELETE CASCADE,
    type            VARCHAR(30) NOT NULL,  -- GOV_ID, ADDRESS_PROOF, WORK_CERTIFICATE
    file_url        VARCHAR(512) NOT NULL,
    original_name   VARCHAR(200),
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    review_note     VARCHAR(400),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_pro_docs_pro ON professional_documents(professional_id);

CREATE TABLE professional_bank_accounts (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL UNIQUE REFERENCES professional_profiles(id) ON DELETE CASCADE,
    method          VARCHAR(10) NOT NULL,  -- UPI, BANK
    upi_id          VARCHAR(120),
    account_name    VARCHAR(120),
    account_number  VARCHAR(40),
    ifsc            VARCHAR(20),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

-- ---------- Bookings ----------
CREATE TABLE bookings (
    id                  UUID PRIMARY KEY,
    code                VARCHAR(20) NOT NULL UNIQUE,
    customer_id         UUID NOT NULL REFERENCES users(id),
    professional_id     UUID REFERENCES users(id),
    category_id         UUID NOT NULL REFERENCES service_categories(id),
    scheduled_date      DATE NOT NULL,
    slot_start          TIME NOT NULL,
    slot_end            TIME NOT NULL,
    address_line        VARCHAR(300),
    city                VARCHAR(80),
    latitude            DOUBLE PRECISION,
    longitude           DOUBLE PRECISION,
    problem_description TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    amount              NUMERIC(12,2) NOT NULL DEFAULT 0,
    commission          NUMERIC(12,2) NOT NULL DEFAULT 0,
    pro_earning         NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_method      VARCHAR(10),
    cancellation_reason VARCHAR(300),
    cancelled_by        VARCHAR(20),
    confirmed_at        TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_bookings_customer ON bookings(customer_id);
CREATE INDEX idx_bookings_pro ON bookings(professional_id);
CREATE INDEX idx_bookings_status ON bookings(status);

CREATE TABLE booking_photos (
    id          UUID PRIMARY KEY,
    booking_id  UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    type        VARCHAR(10) NOT NULL,  -- PROBLEM, WORK
    file_url    VARCHAR(512) NOT NULL,
    uploaded_by UUID REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_booking_photos_booking ON booking_photos(booking_id);

CREATE TABLE booking_status_history (
    id          UUID PRIMARY KEY,
    booking_id  UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL,
    note        VARCHAR(300),
    changed_by  UUID REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_booking_history_booking ON booking_status_history(booking_id);

-- ---------- Chat ----------
CREATE TABLE chat_threads (
    id              UUID PRIMARY KEY,
    booking_id      UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    customer_id     UUID NOT NULL REFERENCES users(id),
    professional_id UUID NOT NULL REFERENCES users(id),
    last_message_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_threads_customer ON chat_threads(customer_id);
CREATE INDEX idx_threads_pro ON chat_threads(professional_id);

CREATE TABLE chat_messages (
    id          UUID PRIMARY KEY,
    thread_id   UUID NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
    sender_id   UUID NOT NULL REFERENCES users(id),
    content     TEXT NOT NULL,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_messages_thread ON chat_messages(thread_id);

-- ---------- Wallet & payments ----------
CREATE TABLE wallets (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    balance     NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency    VARCHAR(3) NOT NULL DEFAULT 'INR',
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE wallet_transactions (
    id              UUID PRIMARY KEY,
    wallet_id       UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    type            VARCHAR(10) NOT NULL,  -- CREDIT, DEBIT
    reason          VARCHAR(30) NOT NULL,  -- TOPUP, BOOKING_PAYMENT, REFUND, PAYOUT, EARNING, ADJUSTMENT
    amount          NUMERIC(12,2) NOT NULL,
    balance_after   NUMERIC(12,2) NOT NULL,
    reference_id    UUID,
    description     VARCHAR(200),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_wallet_txn_wallet ON wallet_transactions(wallet_id);

CREATE TABLE payments (
    id                  UUID PRIMARY KEY,
    booking_id          UUID REFERENCES bookings(id),
    customer_id         UUID NOT NULL REFERENCES users(id),
    gateway             VARCHAR(20) NOT NULL DEFAULT 'MOCK',
    gateway_order_id    VARCHAR(80),
    gateway_payment_id  VARCHAR(80),
    amount              NUMERIC(12,2) NOT NULL,
    currency            VARCHAR(3) NOT NULL DEFAULT 'INR',
    method              VARCHAR(10),
    status              VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    purpose             VARCHAR(20) NOT NULL DEFAULT 'BOOKING', -- BOOKING, WALLET_TOPUP
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_payments_booking ON payments(booking_id);
CREATE INDEX idx_payments_customer ON payments(customer_id);

CREATE TABLE payouts (
    id              UUID PRIMARY KEY,
    professional_id UUID NOT NULL REFERENCES users(id),
    amount          NUMERIC(12,2) NOT NULL,
    method          VARCHAR(10) NOT NULL,  -- UPI, BANK
    destination     VARCHAR(160),
    status          VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    failure_reason  VARCHAR(300),
    processed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_payouts_pro ON payouts(professional_id);

-- ---------- Reviews ----------
CREATE TABLE reviews (
    id              UUID PRIMARY KEY,
    booking_id      UUID NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    customer_id     UUID NOT NULL REFERENCES users(id),
    professional_id UUID NOT NULL REFERENCES users(id),
    rating          INT NOT NULL,
    comment         VARCHAR(1000),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_reviews_pro ON reviews(professional_id);

-- ---------- Offers ----------
CREATE TABLE offers (
    id              UUID PRIMARY KEY,
    code            VARCHAR(40) NOT NULL UNIQUE,
    title           VARCHAR(120) NOT NULL,
    description     VARCHAR(300),
    discount_type   VARCHAR(10) NOT NULL,  -- PERCENT, FLAT
    discount_value  NUMERIC(12,2) NOT NULL,
    max_discount    NUMERIC(12,2),
    min_order       NUMERIC(12,2) NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from      TIMESTAMPTZ,
    valid_to        TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

-- ---------- Disputes ----------
CREATE TABLE disputes (
    id              UUID PRIMARY KEY,
    booking_id      UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    raised_by       UUID NOT NULL REFERENCES users(id),
    reason          VARCHAR(120) NOT NULL,
    description     VARCHAR(1000),
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolution_note VARCHAR(1000),
    resolved_by     UUID REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_disputes_status ON disputes(status);

-- ---------- Notifications ----------
CREATE TABLE notifications (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type        VARCHAR(40) NOT NULL,
    title       VARCHAR(160) NOT NULL,
    body        VARCHAR(500),
    data        TEXT,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_notifications_user ON notifications(user_id);

CREATE TABLE device_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(400) NOT NULL UNIQUE,
    platform    VARCHAR(16) NOT NULL,  -- ANDROID, IOS, WEB
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_device_tokens_user ON device_tokens(user_id);
